"""SQL Validator Agent - Validates SQL syntax."""
import sqlglot
from google.adk.agents import BaseAgent
from google.adk.events import Event
from google.genai import types


class SqlValidatorAgent(BaseAgent):
    name: str = "sql_validator_agent"
    async def _run_async_impl(self, ctx):
        sql = ctx.session.state.get("sql_query")
        if not sql or sql.strip().upper() in ["INCORRECT", "INCORRECT;"]:
            ctx.session.state["sql_valid"], ctx.session.state["validation_error"] = False, "Missing or invalid SQL query generated."
            yield Event(author=self.name, content=types.Content(parts=[types.Part(text="❌ Validation Failed: No valid SQL query was generated by the SQL Architect.")]))
            return
        try:
            sqlglot.transpile(sql, read="sqlite", write="sqlite")[0]
            ctx.session.state["sql_valid"], ctx.session.state["validation_error"] = True, None
            yield Event(author=self.name, content=types.Content(parts=[types.Part(text=f"✓ SQL Syntax Valid: Query passed validation checks.\n\nQuery: {sql}")]))
        except Exception as e:
            ctx.session.state["sql_valid"], ctx.session.state["validation_error"] = False, str(e)
            yield Event(author=self.name, content=types.Content(parts=[types.Part(text=f"❌ SQL Syntax Error: {str(e)}\n\nProblematic Query: {sql}")]))
